### ISSUE TITLE
Add proxy_abi_version_X_Y_Z

### ISSUE THREAD

**Issue by PiotrSikora** [solo-io/proxy-runtime#1]
Please export `proxy_abi_version_0_1_0()` function, otherwise recent versions of proxy (including upcoming Istio Proxy 1.5.0) won't be able to load extensions written using this SDK.

See: https://github.com/envoyproxy/envoy-wasm/pull/438

@yuval-k @ilevine

**Comment by mariopmartins** [comment]
Hi @PiotrSikora, 

I think @yuval-k added that function already at: https://github.com/solo-io/proxy-runtime/blob/master/assembly/exports.ts#L13.

I'm just trying to help here. I'm studying the project you guys are working on and evaluating the language we should use to write our envoy filter HTTP plugin.
BTW, It would be great to hear your thoughts about it. 

Thanks, 
Mario

**Comment by yuval-k** [comment]
this was added. closing as solved; thank you @PiotrSikora and @mariopmartins
