### ISSUE TITLE
Request headers are gone in onResponse()

### ISSUE THREAD

**Issue by esnible** [solo-io/proxy-runtime#26]
In my onRequest(), `stream_context.headers.request.get_headers().length` is 7.
In my onResponse(), it is 0.

If I save the request headers in onRequest(), e.g. `this.originalRequestHeaders = stream_context.headers.request.get_headers()`, they stick around and retain their values.

**Comment by yuval-k** [comment]
i'm not sure what would cause this as this function directly translates to 
```
get_header_map_pairs(RequestHeaders);
```
so it must be that the host sdk code does not make the request headers available on that time; i.e. i don't think we can do anything in this sdk to change this behavior

**Comment by yuval-k** [comment]
see here:
https://github.com/envoyproxy/envoy/blob/78dfea2cc80da8a89d868dc87a4b14f48d141500/source/extensions/common/wasm/context.cc#L1583

the request headers become inaccessible if you continue the request on request headers
