### ISSUE TITLE
File '~lib/rt/index-full.ts' not found

### ISSUE THREAD

**Issue by feuyeux** [solo-io/proxy-runtime#36]
When I did execute build as the below cmd, 
```bash
npm run asbuild:filter
```

I got the error as below:
```bash
ERROR TS6054: File '~lib/rt/index-full.ts' not found.

 } from "rt/index-full";
        ~~~~~~~~~~~~~~~
 in ~lib/@solo-io/proxy-runtime/malloc.ts(4,8)
```
my testing project : https://github.com/feuyeux/assemblyscript-wasm-4-envoy/blob/main/package.json

**Comment by chandlernine** [comment]
Speaking as a fellow user of this module, assemblyscript 0.14.9 is what this module was tested against. You are using a later version which includes commit https://github.com/AssemblyScript/assemblyscript/commit/b85794456b74cd3dff4d39fcd4f9ca3b69b63bec which removed index-full.ts in favor of a new garbage collector. You need to use assemblyscript 0.14.9 or alter this module.

**Comment by feuyeux** [comment]
> AssemblyScript/assemblyscript@b857944

Thanks a lot @chandlernine ! I will redefine the dependencies accordingly.
It could be better if there's a tutorial always tell us the newest proxy-runtime version and it's assemblyscript version.
