### ISSUE TITLE
Envoy has a memory leak because the V8 WASM VMs have memory leaks

### ISSUE THREAD

**Issue by chandlernine** [solo-io/proxy-runtime#40]
The good news is that a hypermodern Assemblyscript 0.18 fixes the leak if you use the default, incremental GC.

To reproduce: Install the same .wasm optimized binary as an HTTP filter on, say, a fortio echosrv in an Istio 1.9.1-enabled namespace. Tell https://github.com/rakyll/hey or equivalent to send traffic to the echosrv. Watch memory rising steadily on the echosrv's istio-proxy until the filter is uninstalled, eventually hitting the 1GB hard limit Istio 1.9.1 imposes and causing Kubernetes to restart the container.

This leak is present in older Istio versions too.

I have tried explicitly calling '__collect()' when creating a new stream context, and it does not change anything.

https://github.com/chandlernine/proxy-runtime/pull/1 shows a fix, which is to use a more recent AssemblyScript with a revamped incremental GC. I'm not sure how one would solve this for AS 0.14's very different memory manager.

**Comment by yuval-k** [comment]
thanks for digging into this; once i'll upgrade to 0.18 will update with your patch

**Comment by chandlernine** [comment]
Our AS 0.18 experiences with both HTTP and NETWORK_FILTER are very promising, although we run a fork at ABI 0.1.0 to be able to work with as old an Istio as possible. I suspect the upgrade will be smooth.

I wish it were easier to use https://github.com/jtenner/as-pect to test this code, but I don't have the skill yet to "mock" a response from a call into the Envoy WASM ABI.

**Comment by kdorosh** [comment]
resolved by https://github.com/solo-io/proxy-runtime/pull/61
