### ISSUE TITLE
gRPC streaming support

### ISSUE THREAD

**Issue by NomadXD** [solo-io/proxy-runtime#41]
Any support for gRPC bidi streaming ? If so, is there any example filter to demonstrate ? Thanks.

**Comment by chandlernine** [comment]
Fellow user here. AFAIK there is no protobuf library for AssemblyScript. This module has its GRPC support commented out.

**Comment by NomadXD** [comment]
@chandlernine Thanks a lot. I decided to use C++ SDK which has support for gRPC
