### ISSUE TITLE
request header can't be retrieved from onResponseHeaders

### ISSUE THREAD

**Issue by amiramw** [solo-io/proxy-runtime#43]
When calling `stream_context.headers.request.get(<key>)` from `onResponseHeaders` the returned header value is empty.
The same API works fine when called from `onRequestHeaders`.

Is it intentional or a bug?

**Comment by yuval-k** [comment]
it is intentional. you cannot get request headers once they are sent upstream. i.e. this is in the abi level (will behave the same in other SDKs)
