### ISSUE TITLE
Using shared queues

### ISSUE THREAD

**Issue by FrankTaylorLieder** [solo-io/proxy-runtime#56]
Hi,

I am trying to use the shared_queue functionality of the Envoy plugins to
enable communication between an HTTP extension and a Service extension.

Firstly, I don't see the relevant calls exposed in the module exports. I had
to use this additional import to get to it:

  import { register_shared_queue, resolve_shared_queue } from "@solo-io/proxy-runtime/runtime";

Is this expected?

Secondly, I could not see how to use these APIs to get the queue ID. In
the end I made the following changes in runtime.ts:

        class QueueResult {
          result: WasmResultValues;
          token: u32;
        }

        export function register_shared_queue(queue_name: string): QueueResult {
          let qid = globalU32Ref;
          let queue_name_buffer = String.UTF8.encode(queue_name);
          let r = imports.proxy_register_shared_queue(changetype<usize>(queue_name_buffer), queue_name_buffer.byteLength, qid.ptr());
          return { result: r, token: qid.data };
        }

        export function resolve_shared_queue(vm_id: string, queue_name: string): QueueResult {
          let qid = globalU32Ref;
          let vm_id_buffer = String.UTF8.encode(vm_id);
          let queue_name_buffer = String.UTF8.encode(queue_name);
          let r = imports.proxy_resolve_shared_queue(changetype<usize>(vm_id_buffer), vm_id_buffer.byteLength,
            changetype<usize>(queue_name_buffer), queue_name_buffer.byteLength, qid.ptr());
          return { result: r, token: qid.data };
        }

Am I missing something?

If not, should I submit this as a pull request?

Thanks,

Frank.

**Comment by yuval-k** [comment]
A PR would be appreciated!
thank you!

**Comment by FrankTaylorLieder** [comment]
It would be good for the project to choose a license type under which the code is made available. I need to get company clearance for contributions, without a defined license type this may be difficult.

**Comment by Sodman** [comment]
Hi @FrankTaylorLieder, we've [added a license](https://github.com/solo-io/proxy-runtime/pull/57/files) (Apache 2.0) to the repo now! Hope that helps.

**Comment by FrankTaylorLieder** [comment]
> Hi @FrankTaylorLieder, we've [added a license](https://github.com/solo-io/proxy-runtime/pull/57/files) (Apache 2.0) to the repo now! Hope that helps.

Thanks. I'll progress getting the contribution sorted.

**Comment by frankt-vmware** [comment]
Hi. I've just created a PR from my company github account. Let me know if anything else is needed. Thanks.

**Comment by yuval-k** [comment]
fixed by https://github.com/solo-io/proxy-runtime/pull/58
thank you!
